# settings.yaml

# Уровень логирования: DEBUG, INFO, WARNING, ERROR
log_level: "WARNING"

# Автоматически применять миграции БД при старте бота
migrations_auto: true

# Имя бота в таблице bots (используется для резолва bot_id)
bot_name: "@banya_sveta_bot"

# Информационный канал (username), из которого копируются сообщения
channel_info: "@banya_sveta_info"

# Основной канал (username) для проверки подписки
channel_main: "@banya_sveta_krd"

# Ссылка на канал (кнопки «Подписаться» / «Перейти на канал»)
channel_url: "https://t.me/+sa8YSpe4XGthN2Vi"

# Настройки PostgreSQL
pg_host: "localhost"
pg_port: 5432
pg_database: "labots"
pg_username: "postgres"
# PG_PASSWORD лучше хранить в .env, но можно и здесь, если файл не в git
